### ISSUE TITLE
Container aware interface?

### ISSUE THREAD

**Issue by eddieajau** [thephpleague/di#3]
I'm just wondering if it's worth adding a ContainerAwareInterface (methods `getContainer` and `setContainer`)?  I'm just trying to imagine how to correctly pass the container around without using a singleton.

So, for example, an Application class might create a container and bind a database connection and let's say a user type object.  The application could create a controller to execute the application, but before it does, it could invoke 

``` php
$controller->setContainer($this->container);
```

or similar.  Or, it could do this:

``` php
if ($controller instanceof ContainerAwareInterface)
{
    $controller->setContainer($this->container);
}

$controller->execute();
```

Thoughts?

**Comment by dongilbert** [comment]
Seems reasonable. I don't mind controllers accessing the container, since they sort of require it to be able to do their job of building and coordinating the request to the response. 
—

**Comment by eddieajau** [comment]
So, for contributing, you "should" follow PSR-2 or you "must" follow PSR-2? :P

**Comment by dongilbert** [comment]
Preferred, but if you can't/don't I'll just pull it locally and run `php-cs-fixer` on it and then merge.

**Comment by philsturgeon** [comment]
Theres a PR for this so we can close the issue.
